import { Swimmer } from "@/models/swimmer";
import { Component, Vue } from "vue-property-decorator";

@Component
class TestDataMixin extends Vue {
    public getTestData(): Swimmer[]{
        return [
            {
               "id":4690063,
               "firstName":"Marije",
               "lastName":"Jansen",
               "birthYear":1985,
               "gender":0,
               "clubName":"Zpc Amersfoort",
               "shortCourseTimes": undefined,
               "longCourseTimes": undefined,
               "position": 0,
               "time": 0,
            },
            {
               "id":4054896,
               "firstName":"Jeroen",
               "lastName":"Zelsmann",
               "birthYear":1977,
               "gender":1,
               "clubName":"Zpc Amersfoort",
               "shortCourseTimes": undefined,
               "longCourseTimes": undefined,
               "position": 0,
               "time": 0
            },
            {
               "id":4278204,
               "firstName":"Loekie",
               "lastName":"Huissteden van",
               "birthYear":1945,
               "gender":0,
               "clubName":"Zpc Amersfoort",
               "shortCourseTimes": undefined,
               "longCourseTimes": undefined,
               "position": 0,
               "time": 0
            },
            {
               "id":4325838,
               "firstName":"Lidia",
               "lastName":"Bon-rosenbrand van",
               "birthYear":1970,
               "gender":0,
               "clubName":"Zpc Amersfoort",
               "shortCourseTimes": undefined,
               "longCourseTimes": undefined,
               "position": 0,
               "time": 0
            },
            {
               "id":4090844,
               "firstName":"Edwin",
               "lastName":"Norden van",
               "birthYear":1963,
               "gender":1,
               "clubName":"Zpc Amersfoort",
               "shortCourseTimes": undefined,
               "longCourseTimes": undefined,
               "position": 0,
               "time": 0
            },
            {
               "id":4041592,
               "firstName":"Henriette",
               "lastName":"Norden van",
               "birthYear":1968,
               "gender":0,
               "clubName":"Zpc Amersfoort",
               "shortCourseTimes": undefined,
               "longCourseTimes": undefined,
               "position": 0,
               "time": 0
            },
            {
               "id":4181922,
               "firstName":"Petra",
               "lastName":"Casteleijn-frowijn",
               "birthYear":1966,
               "gender":0,
               "clubName":"Zpc Amersfoort",
               "shortCourseTimes": undefined,
               "longCourseTimes": undefined,
               "position": 0,
               "time": 0
            },
            {
               "id":4480766,
               "firstName":"Jelle",
               "lastName":"Blankestijn",
               "birthYear":1998,
               "gender":1,
               "clubName":"Zpc Amersfoort",
               "shortCourseTimes": undefined,
               "longCourseTimes": undefined,
               "position": 0,
               "time": 0
            },
            {
               "id":4065141,
               "firstName":"Larissa",
               "lastName":"Brak",
               "birthYear":1988,
               "gender":0,
               "clubName":"Zpc Amersfoort",
               "shortCourseTimes": undefined,
               "longCourseTimes": undefined,
               "position": 0,
               "time": 0
            },
            {
               "id":4065061,
               "firstName":"Erwin",
               "lastName":"Buist",
               "birthYear":1978,
               "gender":1,
               "clubName":"Zpc Amersfoort",
               "shortCourseTimes": undefined,
               "longCourseTimes": undefined,
               "position": 0,
               "time": 0
            },
            {
               "id":4800925,
               "firstName":"Lesley",
               "lastName":"Cordial",
               "birthYear":1967,
               "gender":0,
               "clubName":"Zpc Amersfoort",
               "shortCourseTimes": undefined,
               "longCourseTimes": undefined,
               "position": 0,
               "time": 0
            },
            {
               "id":4296941,
               "firstName":"Lotte",
               "lastName":"Eising",
               "birthYear":1995,
               "gender":0,
               "clubName":"Zpc Amersfoort",
               "shortCourseTimes": undefined,
               "longCourseTimes": undefined,
               "position": 0,
               "time": 0
            },
            {
               "id":4042638,
               "firstName":"Joanne",
               "lastName":"Essen van",
               "birthYear":1993,
               "gender":0,
               "clubName":"Zpc Amersfoort",
               "shortCourseTimes": undefined,
               "longCourseTimes": undefined,
               "position": 0,
               "time": 0
            },
            {
               "id":4356043,
               "firstName":"Martijn",
               "lastName":"Giezen",
               "birthYear":1985,
               "gender":1,
               "clubName":"Zpc Amersfoort",
               "shortCourseTimes": undefined,
               "longCourseTimes": undefined,
               "position": 0,
               "time": 0
            },
            {
               "id":4321877,
               "firstName":"Eline",
               "lastName":"Hendriks",
               "birthYear":1998,
               "gender":0,
               "clubName":"Zpc Amersfoort",
               "shortCourseTimes": undefined,
               "longCourseTimes": undefined,
               "position": 0,
               "time": 0
            },
            {
               "id":4215692,
               "firstName":"Daphne",
               "lastName":"Kievit",
               "birthYear":1992,
               "gender":0,
               "clubName":"Zpc Amersfoort",
               "shortCourseTimes": undefined,
               "longCourseTimes": undefined,
               "position": 0,
               "time": 0
            },
            {
               "id":5243414,
               "firstName":"Monica",
               "lastName":"Korndewal-van beveren",
               "birthYear":1977,
               "gender":0,
               "clubName":"Zpc Amersfoort",
               "shortCourseTimes": undefined,
               "longCourseTimes": undefined,
               "position": 0,
               "time": 0
            },
            {
               "id":4246638,
               "firstName":"Ron",
               "lastName":"Korzelius",
               "birthYear":1965,
               "gender":1,
               "clubName":"Zpc Amersfoort",
               "shortCourseTimes": undefined,
               "longCourseTimes": undefined,
               "position": 0,
               "time": 0
            },
            {
               "id":4841070,
               "firstName":"Henk",
               "lastName":"Kuipers",
               "birthYear":1962,
               "gender":1,
               "clubName":"Zpc Amersfoort",
               "shortCourseTimes": undefined,
               "longCourseTimes": undefined,
               "position": 0,
               "time": 0
            },
            {
               "id":4627173,
               "firstName":"Catannia",
               "lastName":"Nortan",
               "birthYear":1999,
               "gender":0,
               "clubName":"Zpc Amersfoort",
               "shortCourseTimes": undefined,
               "longCourseTimes": undefined,
               "position": 0,
               "time": 0
            },
            {
               "id":4269266,
               "firstName":"Ronald",
               "lastName":"Pijtak",
               "birthYear":1961,
               "gender":1,
               "clubName":"Zpc Amersfoort",
               "shortCourseTimes": undefined,
               "longCourseTimes": undefined,
               "position": 0,
               "time": 0
            },
            {
               "id":4182330,
               "firstName":"Atie",
               "lastName":"Pijtak-radersma",
               "birthYear":1956,
               "gender":0,
               "clubName":"Zpc Amersfoort",
               "shortCourseTimes": undefined,
               "longCourseTimes": undefined,
               "position": 0,
               "time": 0
            },
            {
               "id":4090897,
               "firstName":"Rob",
               "lastName":"Vliet van",
               "birthYear":1984,
               "gender":1,
               "clubName":"Zpc Amersfoort",
               "shortCourseTimes": undefined,
               "longCourseTimes": undefined,
               "position": 0,
               "time": 0
            },
            {
               "id":4916556,
               "firstName":"Marjan",
               "lastName":"Remmits-de lange",
               "birthYear":1963,
               "gender":0,
               "clubName":"Zpc Amersfoort",
               "shortCourseTimes": undefined,
               "longCourseTimes": undefined,
               "position": 0,
               "time": 0
            },
            {
               "id":4681758,
               "firstName":"Johan",
               "lastName":"Remmits",
               "birthYear":1962,
               "gender":1,
               "clubName":"Zpc Amersfoort",
               "shortCourseTimes": undefined,
               "longCourseTimes": undefined,
               "position": 0,
               "time": 0
            },
            {
               "id":4397132,
               "firstName":"Jelle",
               "lastName":"Opmeer",
               "birthYear":2001,
               "gender":1,
               "clubName":"Zpc Amersfoort",
               "shortCourseTimes": undefined,
               "longCourseTimes": undefined,
               "position": 0,
               "time": 0
            },
            {
               "id":4064970,
               "firstName":"Vincent",
               "lastName":"Bakker",
               "birthYear":1986,
               "gender":1,
               "clubName":"Zpc Amersfoort",
               "shortCourseTimes": undefined,
               "longCourseTimes": undefined,
               "position": 0,
               "time": 0
            },
            {
               "id":4658952,
               "firstName":"Elisah",
               "lastName":"Velgersdijk",
               "birthYear":2001,
               "gender":0,
               "clubName":"Zpc Amersfoort",
               "shortCourseTimes": undefined,
               "longCourseTimes": undefined,
               "position": 0,
               "time": 0
            },
            {
               "id":4041424,
               "firstName":"Chester",
               "lastName":"Marsman",
               "birthYear":1969,
               "gender":1,
               "clubName":"Zpc Amersfoort",
               "shortCourseTimes": undefined,
               "longCourseTimes": undefined,
               "position": 0,
               "time": 0
            },
            {
               "id":4343853,
               "firstName":"Mark",
               "lastName":"Eligh",
               "birthYear":1957,
               "gender":1,
               "clubName":"Zpc Amersfoort",
               "shortCourseTimes": undefined,
               "longCourseTimes": undefined,
               "position": 0,
               "time": 0
            },
            {
               "id":4355915,
               "firstName":"Jisca",
               "lastName":"Majolee",
               "birthYear":1994,
               "gender":0,
               "clubName":"Zpc Amersfoort",
               "shortCourseTimes": undefined,
               "longCourseTimes": undefined,
               "position": 0,
               "time": 0
            },
            {
               "id":5352550,
               "firstName":"Rosanne",
               "lastName":"Bakker",
               "birthYear":1988,
               "gender":0,
               "clubName":"Zpc Amersfoort",
               "shortCourseTimes": undefined,
               "longCourseTimes": undefined,
               "position": 0,
               "time": 0
            },
            {
               "id":4893355,
               "firstName":"Jenny",
               "lastName":"Bergwerff",
               "birthYear":1972,
               "gender":0,
               "clubName":"Zpc Amersfoort",
               "shortCourseTimes": undefined,
               "longCourseTimes": undefined,
               "position": 0,
               "time": 0
            }
         ]
    }
}

export default TestDataMixin